language: elixir

elixir:
  - '1.6.0'
otp_release: '20.0'

matrix:
  include:
    - elixir: '1.3.4'
      otp_release: '18.3'
    - elixir: '1.3.4'
      otp_release: '19.0'
    - elixir: '1.6.0'
      otp_release: '20.0'
